### ISSUE TITLE
Microphone Guardian version doesn't work

### ISSUE THREAD

**Issue by Nekropl** [Novecento99/gaming-voice-guardian#10]
I'll describe the problem - microphone guardian correctly recognizes all sound devices on the computer, but when the sound crosses the threashold no sound occurs (although supposedly there should be a monkey sound like in Scymia.exe), and the GUI looks different from the one shown on the Readme page.
![Без имени](https://github.com/user-attachments/assets/3f490538-e46b-4a25-8c1b-c0692ec9dc3e)

**Comment by Novecento99** [comment]
Hi, the GUI looks different because I've updated it and didn't take another screenshot to update the Readme. 
is the output correctly set? moreoever, what happens if you click "debug" ? it should make a bip

**Comment by Nekropl** [comment]
> Hi, the GUI looks different because I've updated it and didn't take another screenshot to update the Readme. is the output correctly set? moreoever, what happens if you click "debug" ? it should make a bip

You were right, at first there was no sound when I pressed the “debug” button, but then I looked more closely at the output devices and for some reason there are many more than I have on my computer (for some reason they are duplicated) and on one of the copies the sound appeared, thank you very much. (But it would be nice if the program could remember the last selected I/O devices)

**Comment by Novecento99** [comment]
yes, it would be better. 
I will implement it thankyou
