### ISSUE TITLE
Multiple mics support has to be implemented

### ISSUE THREAD

**Issue by KaroThanant** [Novecento99/gaming-voice-guardian#6]
I know this is an awfully generic title but I don't know how to ohrase it better. It seems that the app is not enabling the threshold. I've launched the .exe version on my win10 laptop, set the threshold at 100, but even screaming in my mic does not triggers the sound. 

![image](https://user-images.githubusercontent.com/62934401/188020412-251b6b89-1155-41cc-a0db-a4567f7477e8.png)
The command window displays that. The [   ] at the bottom looks like a mic volume indicator, but it never fills. Nothing moves. Do I do it wrong ?

kudos to you reading that. I wish I had the level of commitment needed to make such an app, much less maintaining it.

**Comment by Novecento99** [comment]
You do it right. I think it has to do with multiple mics recognized by the computer. Scimia just picks the default one

In fact one thing to do would be giving the option to select another one

**Comment by Novecento99** [comment]
just because it doesn't  cost anything: try to set 5 as treshold

**Comment by KaroThanant** [comment]
I tried with 1 and nothing
I also tried with 1000 in case it's à weird inverted scale

**Comment by JLUNDMRK** [comment]
Would it be possible to turn off sound totally (in and out) for say 1 minute if a high sound is detected, then increase to 15 min and then 30 min at the third time. My son is yelling when gaming, waking the rest of the family.

**Comment by Novecento99** [comment]
Hi! It's actually a good Idea. 

here someone said how to [control the volume](https://stackoverflow.com/a/63137831)

**Comment by Novecento99** [comment]
mic selection support added! 
in the new version with graphical interface
